### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Jabzy22** [kruvcraft21/SKScript#1]
Crashes whenever using the script on 5.1.0

**Comment by H3XDaemon** [comment]
GG may have been detected

**Comment by kruvcraft21** [comment]
@Jabzy22 , the game crashes not because of the script, but because of the protection that appeared in the last update

**Comment by JohnnyGrave** [comment]
Any way we can bypass the protection?

**Comment by kruvcraft21** [comment]
@JohnnyGrave, I do not know, maybe there is some information in the community, but I have not seen anything

**Comment by kruvcraft21** [comment]
Added a solution to the problem in README.md
